dynam_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('sub_app.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sub_app/urls.py
from django.urls import path
from . import views

app_name = 'sub_app'
urlpatterns = [
    path('',views.home,name='home'),
    path('addspkear/',views.addspeaker,name='speaker'),
    path('home/',views.starter,name='mwanzo'),
    path('speaker/',views.speaker,name='ongea'),
] 

sub_app/models.py
from django.db import models

# Create your models here.
class Speaker(models.Model):
    spker_name = models.CharField(max_length=100)
    speaker_qt = models.CharField(max_length=100)
    spker_desc = models.CharField(max_length=100)
    spker_img = models.ImageField(upload_to="spkerimgs/")

sub_app/views.py
from django.shortcuts import render,redirect
# import models from sub_app
from sub_app.models import Speaker


# Create your views here.

def home(request):  
    return render(request, 'starter-page.html')
def starter(request):   
    speakers = Speaker.objects.all()
    print(speakers)
    return render(request,'index.html',{"speakers": speakers})
def speaker(request):   
    return render(request, 'speaker-details.html')
def addspeaker (request): 
    if request.method == "POST":
        spker_name = request.POST['spker_name']
        speaker_qt = request.POST['speaker_qt']
        spker_desc = request.POST['spker_desc']
        spker_img = request.FILES['spker_img']
        
        speaker = Speaker(
            spker_name = spker_name,
            speaker_qt = speaker_qt,
            spker_desc = spker_desc,
            spker_img = spker_img,
            
        )
        speaker.save()
        return redirect('/')
         
    return render(request,'add_speak er.html')

    

sub_app/templates/add_speaker.html
{% extends "layout.html" %}{%load static%} {% block body%}
<main class="main">
  <section id="hero" class="hero section dark-background">
    <img
      src="{% static 'assets/img/hero-bg.jpg'%}"
      alt=""
      data-aos="fade-in"
      class=""
    />

    <div class="container d-flex flex-column align-items-center text-center">
      <h2>Add Speaker</h2>
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input
          name="spker_name"
          type="text"
          placeholder="Speaker Name"
          class="form-control"
          required
        />
        <br />
        <input
          name="speaker_qt"
          type="text"
          placeholder="Spker Quote"
          class="form-control"
          required
        /><br />
        <textarea
          name="spker_desc"
          placeholder="Speaker Description"
          class="form-control"
          required
        >
        </textarea>
        <br />
        <input name="spker_img" type="file" required /><br />
        <input type="submit" value="Save" class="btn btn-success" />
      </form>
    </div>
  </section>
</main>

{%endblock%}

sub_app/templates/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>Index - TheEvent Bootstrap Template</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />

    <!-- Favicons -->
    {% comment %}
    <link href="assets/img/favicon.png" rel="icon" />
    {% endcomment %}
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}"
      rel="stylesheet"
    />
    <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet" />
    <link
      href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}"
      rel="stylesheet"
    />

    <!-- Main CSS File -->
    <link href="{% static 'assets/css/main.css'%}" rel="stylesheet" />

    <!-- =======================================================
  * Template Name: TheEvent
  * Template URL: https://bootstrapmade.com/theevent-conference-event-bootstrap-template/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  </head>

  <body class="index-page">
    <header id="header" class="header d-flex align-items-center fixed-top">
      <div
        class="container-fluid container-xl position-relative d-flex align-items-center"
      >
        <a href="index.html" class="logo d-flex align-items-center me-auto">
          <img src="{% static 'assets/img/logo.png' %}" alt="" />
          <!-- Uncomment the line below if you also wish to use an text logo -->
          <!-- <h1 class="sitename">TheEvent</h1>  -->
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li>
              <a href="#hero" class="active">Home<br /></a>
            </li>
            <li><a href="#speakers">Speakers</a></li>
            <li><a href="#schedule">Schedule</a></li>
            <li><a href="#venue">Venue</a></li>
            <li><a href="#hotels">Hotels</a></li>
            <li><a href="#gallery">Gallery</a></li>
            <li class="dropdown">
              <a href="#"
                ><span>Dropdown</span>
                <i class="bi bi-chevron-down toggle-dropdown"></i
              ></a>
              <ul>
                <li><a href="#">Dropdown 1</a></li>
                <li class="dropdown">
                  <a href="#"
                    ><span>Deep Dropdown</span>
                    <i class="bi bi-chevron-down toggle-dropdown"></i
                  ></a>
                  <ul>
                    <li><a href="#">Deep Dropdown 1</a></li>
                    <li><a href="#">Deep Dropdown 2</a></li>
                    <li><a href="#">Deep Dropdown 3</a></li>
                    <li><a href="#">Deep Dropdown 4</a></li>
                    <li><a href="#">Deep Dropdown 5</a></li>
                  </ul>
                </li>
                <li><a href="#">Dropdown 2</a></li>
                <li><a href="#">Dropdown 3</a></li>
                <li><a href="#">Dropdown 4</a></li>
              </ul>
            </li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

        <a class="cta-btn d-none d-sm-block" href="#buy-tickets">Buy Tickets</a>
      </div>
    </header>
    {%block body%} {% endblock %}
    <footer id="footer" class="footer dark-background">
      <div class="footer-top">
        <div class="container">
          <div class="row gy-4">
            <div class="col-lg-4 col-md-6 footer-about">
              <a href="index.html" class="logo d-flex align-items-center">
                <span class="sitename">TheEvent</span>
              </a>
              <div class="footer-contact pt-3">
                <p>A108 Juja Street</p>
                <p>New Juja, NY 535022</p>
                <p class="mt-3">
                  <strong>Phone:</strong> <span>+254 794138974</span>
                </p>
                <p><strong>Email:</strong> <span>bonnix@example.com</span></p>
              </div>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
              <h4>Useful Links</h4>
              <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Terms of service</a></li>
                <li><a href="#">Privacy policy</a></li>
              </ul>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
              <h4>Our Services</h4>
              <ul>
                <li><a href="#">Web Design</a></li>
                <li><a href="#">Web Development</a></li>
                <li><a href="#">Product Management</a></li>
                <li><a href="#">Marketing</a></li>
                <li><a href="#">Graphic Design</a></li>
              </ul>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
              <h4>Hic solutasetp</h4>
              <ul>
                <li><a href="#">Molestiae accusamus iure</a></li>
                <li><a href="#">Excepturi dignissimos</a></li>
                <li><a href="#">Suscipit distinctio</a></li>
                <li><a href="#">Dilecta</a></li>
                <li><a href="#">Sit quas consectetur</a></li>
              </ul>
            </div>

            <div class="col-lg-2 col-md-3 footer-links">
              <h4>Nobis illum</h4>
              <ul>
                <li><a href="#">Ipsam</a></li>
                <li><a href="#">Laudantium dolorum</a></li>
                <li><a href="#">Dinera</a></li>
                <li><a href="#">Trodelas</a></li>
                <li><a href="#">Flexo</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="copyright text-center">
        <div
          class="container d-flex flex-column flex-lg-row justify-content-center justify-content-lg-between align-items-center"
        >
          <div
            class="d-flex flex-column align-items-center align-items-lg-start"
          >
            <div>
              © Copyright <strong><span>TheEvent</span></strong
              >. All Rights Reserved
            </div>
            <div class="credits">
              <!-- All the links in the footer should remain intact. -->
              <!-- You can delete the links only if you purchased the pro version. -->
              <!-- Licensing information: https://bootstrapmade.com/license/ -->
              <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->
              Designed by
              <a href="https://bootstrapmade.com/">Bonface Kiprop</a>
            </div>
          </div>

          <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>
      </div>
    </footer>

    <!-- Scroll Top -->
    <a
      href="#"
      id="scroll-top"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js'%}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>

    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.js'%}"></script>
  </body>
</html>

sub_app/templates/speaker-details.html
{% extends "layout.html" %}{%load static%} {% block body%}

<main class="main">
  <!-- Page Title -->
  <div
    class="page-title"
    data-aos="fade"
    style="background-image: url(assets/img/page-title-bg.webp)"
  >
    <div class="container position-relative">
      <h1>Speaker Details</h1>
      <p>
        Esse dolorum voluptatum ullam est sint nemo et est ipsa porro placeat
        quibusdam quia assumenda numquam molestias.
      </p>
      <nav class="breadcrumbs">
        <ol>
          <li><a href="{% url 'mwanzo'%}">Home</a></li>
          <li class="current">Speaker Details</li>
        </ol>
      </nav>
    </div>
  </div>
  <!-- End Page Title -->

  <!-- Events Section -->
  <section id="events" class="events section">
    <div class="container" data-aos="fade-up" data-aos-delay="100">
      <div class="row">
        <div class="col-md-6">
          <img
            src="{% static 'assets/img/speaker.jpg'%}"
            alt="Speaker"
            class="img-fluid"
          />
        </div>

        <div class="col-md-6">
          <div class="details">
            <h2>Brenden Legros</h2>
            <div class="social">
              <a href=""><i class="bi bi-twitter"></i></a>
              <a href=""><i class="bi bi-facebook"></i></a>
              <a href=""><i class="bi bi-instagram"></i></a>
              <a href=""><i class="bi bi-linkedin"></i></a>
            </div>
            <p>
              Voluptatem perferendis sed assumenda voluptatibus. Laudantium
              molestiae sint. Doloremque odio dolore dolore sit. Quae labore
              alias ea omnis ex expedita sapiente molestias atque. Optio
              voluptas et.
            </p>

            <p>
              Aboriosam inventore dolorem inventore nam est esse. Aperiam
              voluptatem nisi molestias laborum ut. Porro dignissimos eum.
              Tempore dolores minus unde est voluptatum incidunt ut aperiam.
            </p>

            <p>
              Et dolore blanditiis officiis non quod id possimus. Optio non
              commodi alias sint culpa sapiente nihil ipsa magnam. Qui eum alias
              provident omnis incidunt aut. Eius et officia corrupti omnis error
              vel quia omnis velit. In qui debitis autem aperiam voluptates unde
              sunt et facilis.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- /Events Section -->
</main>
{%endblock%}

sub_app/templates/starter-page.html
{% extends "layout.html" %}{%load static%} {% block body%}
<main class="main">
  <!-- Page Title -->
  <div
    class="page-title"
    data-aos="fade"

  >
    <div class="container position-relative">
      <h1>Starter Page</h1>
      <p>
        These pains of delight are to be avoided, for they are themselves
        harmful, and because they involve assuming certain inconveniences
        without any proper reason
      </p>
      <nav class="breadcrumbs">
        <ol>
          <li><a href="" class="homelink">Home</a></li>
          <li class="current">Starter Page</li>
        </ol>
      </nav>
    </div>
  </div>
  <!-- End Page Title -->
  <!-- Starter Section Section -->
  <section id="starter-section" class="starter-section "style="background-image: url({% static 'assets/img/hotels-2.jpg'%}); color:white; text-shadow: 0 0 10px cyan, 0 0 20px cyan, 0 0 40px cyan, 0 0 80px cyan; ">
    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Welcome To TheEvent</h2>
      <p data-aos="fade-up" data-aos-delay="200" class="fs-2">
        Check for the coming events <br />Click here <br />
      </p>
      <button  type="button" href=""  class="btn btn-primary"><a href="{% url 'sub_app:mwanzo'%}">Home</a></li></button>
      <p data-aos="fade-up" data-aos-delay="200" class="fs-2">
        Go Live Event <br />Click here <br />
      </p>
      <button
        type="button"
        class="btn btn-lg btn-danger"
        data-bs-toggle="popover"
        data-bs-title="Popover title"
        data-bs-content="And here's some amazing content. It's very engaging. Right?"
      >
         <a href="">Go Live</a></li>
      </button>

    </div>
    <!-- End Section Title -->

    <div class="container" data-aos="fade-up"></div>
  </section>
</main>
{%endblock%}